VERBOSE = False
CLI_VERSION = '0.1'
SSH_KEY_PATH = '~/.ssh/id_rsa_cloudhero'

CLOUD_HERO_URI = 'http://s.cloudhero.io'
CLOUD_HERO_TOKEN_ENV_VARIABLE = 'CLOUD_HERO_TOKEN'

CLOUD_HERO_DIR = '~/.herorc'
CLOUD_HERO_TOKEN = CLOUD_HERO_DIR + '/token'
CLOUD_HERO_NODES_CACHE = CLOUD_HERO_DIR + '/cache/nodes'
CLOUD_HERO_ENVIRONMENTS_CACHE = CLOUD_HERO_DIR + '/cache/enviornments'
