#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys

import click
from pyhero import Client

VERBOSE = False
CLI_VERSION = '0.1'

CLOUD_HERO_URI = 'http://s.cloudhero.io:8080'
CLOUD_HERO_TOKEN_ENV_VARIABLE = 'CLOUD_HERO_TOKEN'
CLOUD_HERO_SETTINGS_PATH = '~/.herorc'


def persist_token(user_token):
    """
    Set token environment variable.
    """
    os.environ['CLOUD_HERO_TOKEN'] = user_token
    write(user_token)


def forget_token():
    """
    Unset token environment variable.
    """
    env_token = os.environ.get('CLOUD_HERO_TOKEN', None)
    del env_token
    delete_token()


def write(content):
    """
    Write token to config file.
    """
    # TODO: this needs improvement, we're just setting the token in the file.
    config_file_path = os.path.expanduser(CLOUD_HERO_SETTINGS_PATH)
    with open(config_file_path, "w") as file_handler:
        file_handler.write(content)


def read_token():
    """
    Read CloudHero config file.
    """
    config_file_path = os.path.expanduser(CLOUD_HERO_SETTINGS_PATH)
    if not os.path.isfile(config_file_path):
        return None

    with open(config_file_path, "r") as file_handler:
        token_from_file = file_handler.read()
        return token_from_file.strip().replace('\n', '').replace('\t', '')


def delete_token():
    """
    Remove token.
    """
    config_file_path = os.path.expanduser(CLOUD_HERO_SETTINGS_PATH)
    try:
        os.remove(config_file_path)
    except OSError:
        print('You are already logged out!')


token = os.environ.get(CLOUD_HERO_TOKEN_ENV_VARIABLE)
if not token:
    token = read_token()
cloud_hero = Client(base_url=CLOUD_HERO_URI, token=token,
                    raise_for_status=False,
                    clean_up_arguments=True)


def verify_one_of(kwargs, *args):
    args_for_printing = '/'.join(['--{}'.format(arg) for arg in args])
    arguments_value_list = [kwargs[arg] for arg in args]
    if not any(arguments_value_list):
        sys.exit('At least one of {} is required'.format(args_for_printing))

    arguments_provided = [arg for arg in arguments_value_list if arg]
    if len(arguments_provided) > 1:
        sys.exit('Provide just one of {}'.format(args_for_printing))


def tags_for_pprint(tags):
    if not tags:
        return '-'
    return ', '.join(['{}:{}'.format(key, value)
                      for key, value in tags.items()])


def tags_to_dict(kwargs):
    """
    Updates kwargs with correct `tags` value.
    """
    tags = kwargs.pop('tags', None)
    if not tags:
        return
    dict_tags = {}
    for tag in tags.split(','):
        tag = tag.strip()
        key, value = tag.split(':')
        dict_tags[key] = value
    kwargs['tags'] = dict_tags


def log_response(response):
    if not response:
        return
    if response.get('error'):
        print('ERROR: {error}'.format(**response))
    elif response.get('message'):
        print('{message}'.format(**response))
    elif response.get('id'):
        print('Created "{name}" (ID {id})'.format(**response))


# ------------------------------------------------------------------------
# ROOT-LEVEL
# ------------------------------------------------------------------------
@click.group()
@click.version_option(version=CLI_VERSION, help='Show the version')
@click.help_option('-h', '--help', help='Show usage')
@click.help_option('-v', '--verbose', help='Enable verbose mode')
def hero(**kwargs):
    if kwargs.get('verbose'):
        global VERBOSE
        VERBOSE = True


@hero.command('token', help='See your token')
def show_token():
    print token


# ------------------------------------------------------------------------
# NODES
# ------------------------------------------------------------------------
@hero.group(help='Nodes operations')
def nodes():
    pass


@nodes.command('add', short_help='Add node', help='Add node')
@click.option('-e', '--environment_id', required=True, prompt=True, help='Environment ID')
@click.option('-p', '--packages', prompt=True, help='Packages to be installed on the node')
@click.option('-n', '--name', prompt=True, help='Node name')
@click.option('-t', '--tags', help='Tags to be applied on the node')
@click.option('-s', '--size', help='Node size')
def add_node(**node_kwargs):
    environment_id = node_kwargs.pop('environment_id')
    if node_kwargs.get('packages'):
        node_kwargs['packages'] = node_kwargs['packages'].split(',')
    tags_to_dict(node_kwargs)
    log_response(cloud_hero.add_node(environment_id, [node_kwargs]))


@nodes.command('scale', help='Scale based node')
@click.option('-e', '--environment_id', required=True, prompt=True, help='Environment ID')
@click.option('--name', help='Scale based on an existing node name')
@click.option('--tags', help='Scale based on an existing node tags')
@click.option('--up', help='Scale UP')
@click.option('--down', help='Scale DOWN')
def scale_node(**kwargs):
    verify_one_of(kwargs, 'name', 'tags')
    verify_one_of(kwargs, 'up', 'down')
    if kwargs.get('name') and kwargs.get('down'):
        print('Note that scaling down by name will only remove the selected '
              'node!')
    tags_to_dict(kwargs)

    environment_id = kwargs.pop('environment_id')
    if kwargs.get('up'):
        kwargs['count'] = int(kwargs.pop('up'))
        log_response(cloud_hero.scale_up_node(environment_id, kwargs))
    else:
        kwargs['count'] = int(kwargs.pop('down'))
        log_response(cloud_hero.scale_down_node(environment_id, kwargs))


@nodes.command('ls', short_help='List all your nodes',
               help='List all your nodes')
def list_nodes():
    node_format = ('{node_id:<25}{node_name:<20}'
                   '{environment_id:<25}{environment_name:<20}'
                   '{status:<10}{provider:<10}{public_ip:<17}{private_ip:<17}'
                   '{packages:<15}{tags:<15}')
    print node_format.format(
        node_id='NODE-ID', node_name='NODE-NAME',
        environment_id='ENVIRONMENT-ID', environment_name='ENVIRONMENT-NAME',
        public_ip='PUBLIC-IP', private_ip='PRIVATE-IP',
        status='STATUS', provider='PROVIDER', packages='PACKAGES', tags='TAGS')

    for environment in cloud_hero.list_environments():
        for node in environment['nodes']:
            node_data = {
                'node_id': node['id'],
                'node_name': node['name'],
                'environment_id': environment['id'],
                'environment_name': environment['name'],
                'status': 'TBD',
                'provider': environment['provider']['name'],
                'public_ip': node.get('public_ip', '-'),
                'private_ip': node.get('private_ip', '-'),
                'packages': ','.join(node['packages']),
                'tags': tags_for_pprint(node['tags'])
            }
            print(node_format.format(**node_data))


@nodes.command('delete', short_help='Remove an existing node',
               help='Remove an existing node')
@click.option('-f', '--force', is_flag=True, help='Force remove node')
@click.option('-id', '--node_id', prompt=True,
              help='Node ID to be removed')
def delete_node(**kwargs):
    log_response(cloud_hero.delete_node(kwargs['node_id'], force=True))

# ------------------------------------------------------------------------
# ENVIRONMENTS
# ------------------------------------------------------------------------
@hero.group(help='Environment set-up')
def environments():
    pass


@environments.command('add', short_help='Add environment',
                      help='Add environment')
@click.option('-l', '--location', prompt=True,
              help='Cloud provider location/region for environment')
@click.option('-n', '--name', prompt=True, help='Environment name')
@click.option('-p', '--provider_id', prompt=True,
              help='Select the provider ID')
def add_environment(**kwargs):
    data = {
        'region': kwargs['location'],
        'environment': kwargs['name'],
        'provider_id': kwargs['provider_id']
    }
    log_response(cloud_hero.create_environment(data))


@environments.command('delete', short_help='Remove an existing environment',
                      help='Remove an existing environment')
@click.option('-f', '--force', is_flag=True, default=False,
              help='Force remove environment')
@click.option('-id', '--environment_id', prompt=True,
              help='Environment ID to be removed')
def delete_environment(**kwargs):
    response = cloud_hero.delete_environment(kwargs['environment_id'],
                                             force=True)
    log_response(response)


@environments.command('ls', short_help='List all your environments',
                      help='List all your environments')
def list_environments():
    format_string = ('{id:<30}{name:<20}{os_region:<15}{nodes_count:<10}'
                     '{node[name]:<15}')
    format_string_no_node = ('{id:<30}{name:<20}{os_region:<15}{nodes_count:<10}')
    format_string_node = '{:<70}{node[name]:<15}'
    print (format_string.format(
        id='ENVIRONMENT-ID', name='NAME', os_region='LOCATION',
        nodes_count='NODES', node={'name': 'NODE-NAMES'}))

    for environment in cloud_hero.list_environments():
        environment_nodes = environment['nodes']
        environment['nodes_count'] = len(environment_nodes)
        if not environment_nodes:
            print(format_string_no_node.format(**environment))
            continue
        for index, node in enumerate(environment_nodes):
            environment['node'] = node
            if index == 0:
                print format_string.format(**environment)
                continue
            print(format_string_node.format('', **environment))


# ------------------------------------------------------------------------
# PROVIDERS
# ------------------------------------------------------------------------
@hero.group(help='Cloud providers')
def providers():
    pass


class OptionsBasedCLI(click.MultiCommand):

    def __init__(self, *args, **kwargs):
        self.command_type = kwargs.pop('command_type')
        self.field_type = kwargs.pop('field_type')
        super(OptionsBasedCLI, self).__init__(*args, **kwargs)

    def list_commands(self, ctx):
        rv = cloud_hero.show_options(self.command_type).keys()
        rv.sort()
        return rv

    def get_command(self, ctx, name):
        if name not in self.list_commands(ctx):
            ctx.fail('No such command "%s".' % name)

        api_description = cloud_hero.show_options(self.command_type)
        params = [click.Option((('--name'), ), prompt=True)]
        for mandatory_field in api_description[name]['mandatory_fields']:
            option_args = ('--{}'.format(mandatory_field), )
            click_option = click.Option(option_args, prompt=True)
            params.append(click_option)

        @click.pass_context
        def callback(ctx, **kwargs):
            kwargs[self.field_type] = ctx.info_name
            # Hacks
            if self.command_type == 'providers':
                if 'accesskey' in kwargs:
                    kwargs['accessKey'] = kwargs['accesskey']
                    kwargs['secretKey'] = kwargs['secretkey']

            response = cloud_hero.create_from_options(self.command_type, kwargs)
            log_response(response)

        cmd_return = click.Command(name, params=params, callback=callback,
                                       help=api_description[name]['description'])
        return cmd_return


@providers.command('add', cls=OptionsBasedCLI, command_type='providers',
                   field_type='cloud_provider',
                   short_help='Add a new cloud provider',
                   help='Add a new cloud provider')
@click.pass_context
def add_cloud_provider(ctx, *args, **kwargs):
    pass


@providers.command('ls', short_help='List all configured providers',
                   help='List all configured providers')
@click.option('-k', '--show-keys', is_flag=True, help='Show provider keys')
def list_providers(**kwargs):
    format_string = '{id:<30} {provider_type:<15} {name:<15}'
    if kwargs.get('show_keys'):
        format_string = '{id:<30} {provider_type:<15} {name:<15} {keys:<30}'

    print (format_string.format(provider_type='PROVIDER-TYPE', id='PROVIDER-ID',
                                name='NAME', keys='PROVIDER-KEYS'))

    cloud_providers = cloud_hero.list_providers()
    for provider_type, providers_list in cloud_providers.items():
        for provider in providers_list:
            if provider['provider_type'] == 'ec2':
                provider['keys'] = 'key: {accessKey}, secret: {secretKey}'.format(
                    **provider['provider_meta'])
            else:
                provider['keys'] = provider['provider_meta'].values()[0]
            print(format_string.format(**provider))


@providers.command('delete', short_help='Remove a provider',
                   help='Remove a provider')
@click.option('-id', '--provider_id', prompt=True,
              help='Provider ID to be removed')
def delete_provider(**kwargs):
    log_response(cloud_hero.delete_provider(kwargs['provider_id']))


# ------------------------------------------------------------------------
# INTEGRATIONS
# ------------------------------------------------------------------------
@hero.group(help='Add custom integrations')
def integrations():
    pass


@integrations.command('add', cls=OptionsBasedCLI, command_type='integrations',
                      field_type='type',
                      short_help='Configure a new integration',
                      help='Configure a new integration')
@click.pass_context
def add_integration(ctx, *args, **kwargs):
    pass


@integrations.command('ls', short_help='List all configured integrations',
                      help='List all configured integrations')
def list_integrations():
    string_format = '{id:<30}{type:<20}{name:<15}{meta:<30}'
    print string_format.format(type='INTEGRATION-TYPE', id='INTEGRATION-ID',
                               name='NAME', meta='INTEGRATION-METADATA')
    for integration in cloud_hero.list_integrations():
        integration['meta'] = tags_for_pprint(integration['integration_meta'])
        print string_format.format(**integration)


@integrations.command('delete', short_help='Remove an integration',
                      help='Remove an integration')
@click.option('-id', '--integration_id', prompt=True,
              help='Integration ID to be removed')
def delete_integration(**kwargs):
    cloud_hero.delete_integration(kwargs['integration_id'])


# ------------------------------------------------------------------------
# AUTH-RELATED
# ------------------------------------------------------------------------
@hero.command(short_help='Logout user', help='Logout user')
def logout():
    forget_token()


@hero.command(short_help='Login user', help='Login user')
@click.option('-e', '--email', prompt=True, help='Email')
@click.option('-p', '--password', prompt=True, hide_input=True, help='Password')
def login(**kwargs):
    persist_token(cloud_hero.login(**kwargs))
    print('Let\'s launch some servers!')


@hero.command(short_help='Create account', help='Create account')
@click.option('-u', '--username', prompt=True, help='Username')
@click.option('-p', '--password', prompt=True, confirmation_prompt=True,
              hide_input=True, help='Password')
@click.option('-e', '--email', prompt=True, help='Email')
def register(**kwargs):
    data = cloud_hero.register(kwargs['email'], kwargs['password'],
                               kwargs['username'])

    # Handle registration errors.
    errors = data.get('errors')
    if errors:
        for error_field, error_data in errors.items():
            print('Invalid {:<15} {}'.format(error_field,
                                             error_data[0]))
        sys.exit(1)

    # Persist token.
    user_token = str(data['persistent_token'])
    persist_token(user_token)

    # And welcome user :)
    print('Welcome to CloudHero, {username}!'.format(**kwargs))


if __name__ == '__main__':
    hero()
